// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1015979684;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'smartvault_core',
    ioDirectory: 'native/smartvault_core/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Uint8List crateApiApiDecrypt(
      {required List<int> ciphertextWithNonce, required List<int> key});

  Future<Uint8List> crateApiApiDeriveKey(
      {required List<int> password, required List<int> salt});

  Future<Uint8List> crateApiApiDeriveKeyPbkdf2(
      {required List<int> password, required List<int> salt});

  Uint8List crateApiApiDeriveX25519SharedSecret(
      {required List<int> privateKey, required List<int> peerPublicKey});

  Uint8List crateApiApiEd25519GenerateSigningKey();

  Uint8List crateApiApiEd25519GetVerifyingKey({required List<int> signingKey});

  Uint8List crateApiApiEd25519Sign(
      {required List<int> message, required List<int> signingKey});

  bool crateApiApiEd25519Verify(
      {required List<int> message,
      required List<int> signature,
      required List<int> verifyingKey});

  Uint8List crateApiApiEncrypt(
      {required List<int> plaintext, required List<int> key});

  double crateApiApiFaceCosineSimilarity(
      {required List<double> a, required List<double> b});

  (BigInt, double)? crateApiApiFaceFindBestMatch(
      {required List<double> probe, required List<Float32List> stored});

  bool crateApiApiFaceIsSamePerson(
      {required List<double> a, required List<double> b, double? threshold});

  Float32List crateApiApiFaceNormalizeEmbedding(
      {required List<double> embeddingVec});

  Uint8List crateApiApiGenerateKey();

  Uint8List crateApiApiGenerateNonce();

  String crateApiApiGeneratePassword({required ApiGeneratorConfig config});

  Uint8List crateApiApiGenerateX25519PrivateKey();

  Uint8List crateApiApiGetX25519PublicKey({required List<int> privateKey});

  Future<String> crateApiApiHashPassword({required String password});

  Uint8List crateApiApiSharingDecrypt(
      {required List<int> shareBytes, required List<int> recipientPrivateKey});

  Uint8List crateApiApiSharingEncrypt(
      {required List<int> plaintext, required List<int> recipientPublicKey});

  String crateApiApiTotpGenerate(
      {required String secretBase32, required BigInt timestampSecs});

  String crateApiApiTotpGenerateCustom(
      {required String secretBase32,
      required BigInt timestampSecs,
      required int digits,
      required BigInt period});

  BigInt crateApiApiTotpTimeRemaining({required BigInt timestampSecs});

  BigInt crateApiApiTotpTimeStep({required BigInt timestampSecs});

  Future<bool> crateApiApiVerifyPassword(
      {required String password, required String hash});

  Future<void> crateApiInitApp();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Uint8List crateApiApiDecrypt(
      {required List<int> ciphertextWithNonce, required List<int> key}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(ciphertextWithNonce, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiDecryptConstMeta,
      argValues: [ciphertextWithNonce, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiDecryptConstMeta => const TaskConstMeta(
        debugName: "api_decrypt",
        argNames: ["ciphertextWithNonce", "key"],
      );

  @override
  Future<Uint8List> crateApiApiDeriveKey(
      {required List<int> password, required List<int> salt}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(password, serializer);
        sse_encode_list_prim_u_8_loose(salt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiDeriveKeyConstMeta,
      argValues: [password, salt],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiDeriveKeyConstMeta => const TaskConstMeta(
        debugName: "api_derive_key",
        argNames: ["password", "salt"],
      );

  @override
  Future<Uint8List> crateApiApiDeriveKeyPbkdf2(
      {required List<int> password, required List<int> salt}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(password, serializer);
        sse_encode_list_prim_u_8_loose(salt, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiApiDeriveKeyPbkdf2ConstMeta,
      argValues: [password, salt],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiDeriveKeyPbkdf2ConstMeta => const TaskConstMeta(
        debugName: "api_derive_key_pbkdf2",
        argNames: ["password", "salt"],
      );

  @override
  Uint8List crateApiApiDeriveX25519SharedSecret(
      {required List<int> privateKey, required List<int> peerPublicKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(privateKey, serializer);
        sse_encode_list_prim_u_8_loose(peerPublicKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiDeriveX25519SharedSecretConstMeta,
      argValues: [privateKey, peerPublicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiDeriveX25519SharedSecretConstMeta =>
      const TaskConstMeta(
        debugName: "api_derive_x25519_shared_secret",
        argNames: ["privateKey", "peerPublicKey"],
      );

  @override
  Uint8List crateApiApiEd25519GenerateSigningKey() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiApiEd25519GenerateSigningKeyConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiEd25519GenerateSigningKeyConstMeta =>
      const TaskConstMeta(
        debugName: "api_ed25519_generate_signing_key",
        argNames: [],
      );

  @override
  Uint8List crateApiApiEd25519GetVerifyingKey({required List<int> signingKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(signingKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiEd25519GetVerifyingKeyConstMeta,
      argValues: [signingKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiEd25519GetVerifyingKeyConstMeta =>
      const TaskConstMeta(
        debugName: "api_ed25519_get_verifying_key",
        argNames: ["signingKey"],
      );

  @override
  Uint8List crateApiApiEd25519Sign(
      {required List<int> message, required List<int> signingKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(message, serializer);
        sse_encode_list_prim_u_8_loose(signingKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiEd25519SignConstMeta,
      argValues: [message, signingKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiEd25519SignConstMeta => const TaskConstMeta(
        debugName: "api_ed25519_sign",
        argNames: ["message", "signingKey"],
      );

  @override
  bool crateApiApiEd25519Verify(
      {required List<int> message,
      required List<int> signature,
      required List<int> verifyingKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(message, serializer);
        sse_encode_list_prim_u_8_loose(signature, serializer);
        sse_encode_list_prim_u_8_loose(verifyingKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiEd25519VerifyConstMeta,
      argValues: [message, signature, verifyingKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiEd25519VerifyConstMeta => const TaskConstMeta(
        debugName: "api_ed25519_verify",
        argNames: ["message", "signature", "verifyingKey"],
      );

  @override
  Uint8List crateApiApiEncrypt(
      {required List<int> plaintext, required List<int> key}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(plaintext, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiEncryptConstMeta,
      argValues: [plaintext, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiEncryptConstMeta => const TaskConstMeta(
        debugName: "api_encrypt",
        argNames: ["plaintext", "key"],
      );

  @override
  double crateApiApiFaceCosineSimilarity(
      {required List<double> a, required List<double> b}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_f_32_loose(a, serializer);
        sse_encode_list_prim_f_32_loose(b, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_32,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiFaceCosineSimilarityConstMeta,
      argValues: [a, b],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiFaceCosineSimilarityConstMeta =>
      const TaskConstMeta(
        debugName: "api_face_cosine_similarity",
        argNames: ["a", "b"],
      );

  @override
  (BigInt, double)? crateApiApiFaceFindBestMatch(
      {required List<double> probe, required List<Float32List> stored}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_f_32_loose(probe, serializer);
        sse_encode_list_list_prim_f_32_strict(stored, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_record_usize_f_32,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiFaceFindBestMatchConstMeta,
      argValues: [probe, stored],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiFaceFindBestMatchConstMeta =>
      const TaskConstMeta(
        debugName: "api_face_find_best_match",
        argNames: ["probe", "stored"],
      );

  @override
  bool crateApiApiFaceIsSamePerson(
      {required List<double> a, required List<double> b, double? threshold}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_f_32_loose(a, serializer);
        sse_encode_list_prim_f_32_loose(b, serializer);
        sse_encode_opt_box_autoadd_f_32(threshold, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiFaceIsSamePersonConstMeta,
      argValues: [a, b, threshold],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiFaceIsSamePersonConstMeta =>
      const TaskConstMeta(
        debugName: "api_face_is_same_person",
        argNames: ["a", "b", "threshold"],
      );

  @override
  Float32List crateApiApiFaceNormalizeEmbedding(
      {required List<double> embeddingVec}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_f_32_loose(embeddingVec, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_f_32_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiFaceNormalizeEmbeddingConstMeta,
      argValues: [embeddingVec],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiFaceNormalizeEmbeddingConstMeta =>
      const TaskConstMeta(
        debugName: "api_face_normalize_embedding",
        argNames: ["embeddingVec"],
      );

  @override
  Uint8List crateApiApiGenerateKey() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiApiGenerateKeyConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGenerateKeyConstMeta => const TaskConstMeta(
        debugName: "api_generate_key",
        argNames: [],
      );

  @override
  Uint8List crateApiApiGenerateNonce() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiApiGenerateNonceConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGenerateNonceConstMeta => const TaskConstMeta(
        debugName: "api_generate_nonce",
        argNames: [],
      );

  @override
  String crateApiApiGeneratePassword({required ApiGeneratorConfig config}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_api_generator_config(config, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiGeneratePasswordConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGeneratePasswordConstMeta =>
      const TaskConstMeta(
        debugName: "api_generate_password",
        argNames: ["config"],
      );

  @override
  Uint8List crateApiApiGenerateX25519PrivateKey() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiApiGenerateX25519PrivateKeyConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGenerateX25519PrivateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "api_generate_x25519_private_key",
        argNames: [],
      );

  @override
  Uint8List crateApiApiGetX25519PublicKey({required List<int> privateKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(privateKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiGetX25519PublicKeyConstMeta,
      argValues: [privateKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiGetX25519PublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "api_get_x25519_public_key",
        argNames: ["privateKey"],
      );

  @override
  Future<String> crateApiApiHashPassword({required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiHashPasswordConstMeta,
      argValues: [password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiHashPasswordConstMeta => const TaskConstMeta(
        debugName: "api_hash_password",
        argNames: ["password"],
      );

  @override
  Uint8List crateApiApiSharingDecrypt(
      {required List<int> shareBytes, required List<int> recipientPrivateKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(shareBytes, serializer);
        sse_encode_list_prim_u_8_loose(recipientPrivateKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiSharingDecryptConstMeta,
      argValues: [shareBytes, recipientPrivateKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiSharingDecryptConstMeta => const TaskConstMeta(
        debugName: "api_sharing_decrypt",
        argNames: ["shareBytes", "recipientPrivateKey"],
      );

  @override
  Uint8List crateApiApiSharingEncrypt(
      {required List<int> plaintext, required List<int> recipientPublicKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(plaintext, serializer);
        sse_encode_list_prim_u_8_loose(recipientPublicKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiSharingEncryptConstMeta,
      argValues: [plaintext, recipientPublicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiSharingEncryptConstMeta => const TaskConstMeta(
        debugName: "api_sharing_encrypt",
        argNames: ["plaintext", "recipientPublicKey"],
      );

  @override
  String crateApiApiTotpGenerate(
      {required String secretBase32, required BigInt timestampSecs}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(secretBase32, serializer);
        sse_encode_u_64(timestampSecs, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiTotpGenerateConstMeta,
      argValues: [secretBase32, timestampSecs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiTotpGenerateConstMeta => const TaskConstMeta(
        debugName: "api_totp_generate",
        argNames: ["secretBase32", "timestampSecs"],
      );

  @override
  String crateApiApiTotpGenerateCustom(
      {required String secretBase32,
      required BigInt timestampSecs,
      required int digits,
      required BigInt period}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(secretBase32, serializer);
        sse_encode_u_64(timestampSecs, serializer);
        sse_encode_u_32(digits, serializer);
        sse_encode_u_64(period, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiTotpGenerateCustomConstMeta,
      argValues: [secretBase32, timestampSecs, digits, period],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiTotpGenerateCustomConstMeta =>
      const TaskConstMeta(
        debugName: "api_totp_generate_custom",
        argNames: ["secretBase32", "timestampSecs", "digits", "period"],
      );

  @override
  BigInt crateApiApiTotpTimeRemaining({required BigInt timestampSecs}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(timestampSecs, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiApiTotpTimeRemainingConstMeta,
      argValues: [timestampSecs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiTotpTimeRemainingConstMeta =>
      const TaskConstMeta(
        debugName: "api_totp_time_remaining",
        argNames: ["timestampSecs"],
      );

  @override
  BigInt crateApiApiTotpTimeStep({required BigInt timestampSecs}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(timestampSecs, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiApiTotpTimeStepConstMeta,
      argValues: [timestampSecs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiTotpTimeStepConstMeta => const TaskConstMeta(
        debugName: "api_totp_time_step",
        argNames: ["timestampSecs"],
      );

  @override
  Future<bool> crateApiApiVerifyPassword(
      {required String password, required String hash}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(password, serializer);
        sse_encode_String(hash, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiApiVerifyPasswordConstMeta,
      argValues: [password, hash],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiVerifyPasswordConstMeta => const TaskConstMeta(
        debugName: "api_verify_password",
        argNames: ["password", "hash"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApiGeneratorConfig dco_decode_api_generator_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ApiGeneratorConfig(
      length: dco_decode_usize(arr[0]),
      useLowercase: dco_decode_bool(arr[1]),
      useUppercase: dco_decode_bool(arr[2]),
      useDigits: dco_decode_bool(arr[3]),
      useSymbols: dco_decode_bool(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ApiGeneratorConfig dco_decode_box_autoadd_api_generator_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_generator_config(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  (BigInt, double) dco_decode_box_autoadd_record_usize_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (BigInt, double);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<Float32List> dco_decode_list_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_f_32_strict)
        .toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  (BigInt, double)? dco_decode_opt_box_autoadd_record_usize_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_record_usize_f_32(raw);
  }

  @protected
  (BigInt, double) dco_decode_record_usize_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_usize(arr[0]),
      dco_decode_f_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApiGeneratorConfig sse_decode_api_generator_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_length = sse_decode_usize(deserializer);
    var var_useLowercase = sse_decode_bool(deserializer);
    var var_useUppercase = sse_decode_bool(deserializer);
    var var_useDigits = sse_decode_bool(deserializer);
    var var_useSymbols = sse_decode_bool(deserializer);
    return ApiGeneratorConfig(
        length: var_length,
        useLowercase: var_useLowercase,
        useUppercase: var_useUppercase,
        useDigits: var_useDigits,
        useSymbols: var_useSymbols);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ApiGeneratorConfig sse_decode_box_autoadd_api_generator_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_generator_config(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  (BigInt, double) sse_decode_box_autoadd_record_usize_f_32(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_usize_f_32(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<Float32List> sse_decode_list_list_prim_f_32_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Float32List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_f_32_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (BigInt, double)? sse_decode_opt_box_autoadd_record_usize_f_32(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_record_usize_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (BigInt, double) sse_decode_record_usize_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_usize(deserializer);
    var var_field1 = sse_decode_f_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_generator_config(
      ApiGeneratorConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.length, serializer);
    sse_encode_bool(self.useLowercase, serializer);
    sse_encode_bool(self.useUppercase, serializer);
    sse_encode_bool(self.useDigits, serializer);
    sse_encode_bool(self.useSymbols, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_api_generator_config(
      ApiGeneratorConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_generator_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_usize_f_32(
      (BigInt, double) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_usize_f_32(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_list_prim_f_32_strict(
      List<Float32List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_f_32_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
      List<double> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
        self is Float32List ? self : Float32List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_record_usize_f_32(
      (BigInt, double)? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_record_usize_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_record_usize_f_32(
      (BigInt, double) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.$1, serializer);
    sse_encode_f_32(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}