//! X25519-ECDH + AES-256-GCM encrypted item sharing.
//!
//! Protocol (similar to Noise_X / ECIES):
//!   1. Sender generates an ephemeral X25519 keypair.
//!   2. Derive shared secret: `ss = X25519(sender_ephemeral_sk, recipient_pk)`.
//!   3. Derive AES key: `aes_key = SHA-256(ss || sender_eph_pk || recipient_pk)`.
//!      Using the public keys as context prevents key reuse across sessions.
//!   4. Encrypt with AES-256-GCM.
//!   5. Transmit: `{sender_eph_pk (32 B), nonce (12 B), ciphertext+tag}`.
//!
//! Recipient decryption:
//!   1. `ss = X25519(recipient_sk, sender_eph_pk)`.
//!   2. Rederive `aes_key` with same KDF.
//!   3. Decrypt.

use crate::crypto::{aes_gcm as aes, x25519};
use sha2::{Digest, Sha256};

// ─── Wire format ─────────────────────────────────────────────────────────────

/// One encrypted share — everything the recipient needs to decrypt.
///
/// Serialise as `[sender_ephemeral_pk (32)] [nonce (12)] [ciphertext+tag (N+16)]`.
pub struct EncryptedShare {
    /// Ephemeral X25519 public key generated by the sender.
    pub sender_ephemeral_pk: [u8; 32],
    /// AES-GCM nonce (random, 12 bytes).
    pub nonce: [u8; 12],
    /// AES-GCM ciphertext with appended 16-byte tag.
    pub ciphertext_with_tag: Vec<u8>,
}

impl EncryptedShare {
    /// Serialise to bytes: `sender_eph_pk || nonce || ciphertext_with_tag`.
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(32 + 12 + self.ciphertext_with_tag.len());
        out.extend_from_slice(&self.sender_ephemeral_pk);
        out.extend_from_slice(&self.nonce);
        out.extend_from_slice(&self.ciphertext_with_tag);
        out
    }

    /// Parse from the wire format produced by `to_bytes`.
    pub fn from_bytes(data: &[u8]) -> Option<Self> {
        if data.len() < 32 + 12 + 16 {
            return None; // too short even for empty plaintext
        }
        let mut sender_eph_pk = [0u8; 32];
        let mut nonce = [0u8; 12];
        sender_eph_pk.copy_from_slice(&data[..32]);
        nonce.copy_from_slice(&data[32..44]);
        let ciphertext_with_tag = data[44..].to_vec();
        Some(EncryptedShare { sender_ephemeral_pk: sender_eph_pk, nonce, ciphertext_with_tag })
    }
}

// ─── KDF ─────────────────────────────────────────────────────────────────────

/// Derive a 32-byte AES key from the X25519 shared secret and the two public keys.
///
/// `KDF(ss, sender_pk, recipient_pk) = SHA-256(ss || sender_pk || recipient_pk)`
fn derive_aes_key(shared_secret: &[u8; 32], sender_pk: &[u8; 32], recipient_pk: &[u8; 32]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(shared_secret);
    hasher.update(sender_pk);
    hasher.update(recipient_pk);
    let digest = hasher.finalize();
    let mut key = [0u8; 32];
    key.copy_from_slice(&digest);
    key
}

// ─── Public API ───────────────────────────────────────────────────────────────

/// Errors for sharing operations.
#[derive(Debug, PartialEq)]
pub enum SharingError {
    InvalidKeySize { expected: usize, got: usize },
    EncryptionFailed,
    DecryptionFailed,
    InvalidShareFormat,
}

impl std::fmt::Display for SharingError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SharingError::InvalidKeySize { expected, got } => {
                write!(f, "Invalid key size: expected {expected}, got {got}")
            }
            SharingError::EncryptionFailed => write!(f, "Sharing encryption failed"),
            SharingError::DecryptionFailed  => write!(f, "Sharing decryption failed"),
            SharingError::InvalidShareFormat => write!(f, "Invalid encrypted share format"),
        }
    }
}

/// Encrypt `plaintext` so that only the holder of `recipient_pk`'s private key
/// can decrypt it.
///
/// * `recipient_pk` — 32-byte X25519 public key of the intended recipient.
/// * `plaintext`     — arbitrary byte payload (vault item JSON, etc.).
///
/// Returns an `EncryptedShare` ready to serialise and transmit.
pub fn encrypt_for_recipient(
    plaintext: &[u8],
    recipient_pk: &[u8],
) -> Result<EncryptedShare, SharingError> {
    if recipient_pk.len() != 32 {
        return Err(SharingError::InvalidKeySize { expected: 32, got: recipient_pk.len() });
    }

    // Step 1: ephemeral sender keypair
    let sender_eph_sk = x25519::generate_private_key();
    let sender_eph_pk = x25519::get_public_key(&sender_eph_sk);

    // Step 2: shared secret
    let mut rcp_arr = [0u8; 32];
    rcp_arr.copy_from_slice(recipient_pk);
    let shared_secret = x25519::derive_shared_secret(&sender_eph_sk, &rcp_arr);

    // Step 3: AES key
    let aes_key = derive_aes_key(&shared_secret, &sender_eph_pk, &rcp_arr);

    // Step 4: random nonce + AES-256-GCM encrypt
    let nonce_vec = aes::generate_nonce();
    let mut nonce = [0u8; 12];
    nonce.copy_from_slice(&nonce_vec);

    let ciphertext_with_tag = aes::encrypt_with_nonce(plaintext, &aes_key, &nonce)
        .map_err(|_| SharingError::EncryptionFailed)?;

    Ok(EncryptedShare { sender_ephemeral_pk: sender_eph_pk, nonce, ciphertext_with_tag })
}

/// Decrypt an `EncryptedShare` using the recipient's private key.
///
/// * `share`         — the `EncryptedShare` received from the sender.
/// * `recipient_sk`  — 32-byte X25519 private key of the recipient.
///
/// Returns the decrypted plaintext.
pub fn decrypt_from_sender(
    share: &EncryptedShare,
    recipient_sk: &[u8],
) -> Result<Vec<u8>, SharingError> {
    if recipient_sk.len() != 32 {
        return Err(SharingError::InvalidKeySize { expected: 32, got: recipient_sk.len() });
    }

    // Reconstruct recipient public key from secret for the KDF
    let mut sk_arr = [0u8; 32];
    sk_arr.copy_from_slice(recipient_sk);
    let recipient_pk = x25519::get_public_key(&sk_arr);

    // Shared secret via X25519
    let shared_secret = x25519::derive_shared_secret(&sk_arr, &share.sender_ephemeral_pk);

    // Rederive AES key
    let aes_key = derive_aes_key(&shared_secret, &share.sender_ephemeral_pk, &recipient_pk);

    // Decrypt
    aes::decrypt_with_nonce(&share.ciphertext_with_tag, &aes_key, &share.nonce)
        .map_err(|_| SharingError::DecryptionFailed)
}

// ─── Unit tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_recipient_keypair() -> ([u8; 32], [u8; 32]) {
        let sk = x25519::generate_private_key();
        let pk = x25519::get_public_key(&sk);
        (sk, pk)
    }

    #[test]
    fn test_encrypt_decrypt_roundtrip() {
        let (rcp_sk, rcp_pk) = make_recipient_keypair();
        let plaintext = b"Super secret vault item: { password: 'hunter2' }";

        let share = encrypt_for_recipient(plaintext, &rcp_pk).unwrap();
        let decrypted = decrypt_from_sender(&share, &rcp_sk).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_wrong_recipient_key_fails() {
        let (_rcp_sk, rcp_pk) = make_recipient_keypair();
        let (wrong_sk, _) = make_recipient_keypair();
        let share = encrypt_for_recipient(b"secret", &rcp_pk).unwrap();
        assert!(decrypt_from_sender(&share, &wrong_sk).is_err());
    }

    #[test]
    fn test_each_encryption_uses_unique_ephemeral_key() {
        let (_, rcp_pk) = make_recipient_keypair();
        let s1 = encrypt_for_recipient(b"same payload", &rcp_pk).unwrap();
        let s2 = encrypt_for_recipient(b"same payload", &rcp_pk).unwrap();
        // Ephemeral keys should differ (randomised) → different ciphertexts
        assert_ne!(s1.sender_ephemeral_pk, s2.sender_ephemeral_pk);
        assert_ne!(s1.ciphertext_with_tag, s2.ciphertext_with_tag);
    }

    #[test]
    fn test_serialise_deserialise() {
        let (rcp_sk, rcp_pk) = make_recipient_keypair();
        let plaintext = b"round-trip wire format";
        let share = encrypt_for_recipient(plaintext, &rcp_pk).unwrap();

        // Serialise → deserialise → decrypt
        let bytes = share.to_bytes();
        let share2 = EncryptedShare::from_bytes(&bytes).unwrap();
        let decrypted = decrypt_from_sender(&share2, &rcp_sk).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn test_invalid_share_format_rejected() {
        assert!(EncryptedShare::from_bytes(&[0u8; 10]).is_none()); // too short
    }

    #[test]
    fn test_empty_plaintext() {
        let (rcp_sk, rcp_pk) = make_recipient_keypair();
        let share = encrypt_for_recipient(b"", &rcp_pk).unwrap();
        let decrypted = decrypt_from_sender(&share, &rcp_sk).unwrap();
        assert!(decrypted.is_empty());
    }
}
