// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Generate a random 32-byte AES-256 key.
Uint8List apiGenerateKey() => RustLib.instance.api.crateApiApiGenerateKey();

/// Generate a random 12-byte AES-GCM nonce.
Uint8List apiGenerateNonce() => RustLib.instance.api.crateApiApiGenerateNonce();

/// Encrypt `plaintext` with `key`. Returns `[nonce(12) || ciphertext+tag]`.
///
/// Throws a Dart exception if `key` is not 32 bytes.
Uint8List apiEncrypt({required List<int> plaintext, required List<int> key}) =>
    RustLib.instance.api.crateApiApiEncrypt(plaintext: plaintext, key: key);

/// Decrypt a blob produced by `api_encrypt`.
Uint8List apiDecrypt(
        {required List<int> ciphertextWithNonce, required List<int> key}) =>
    RustLib.instance.api
        .crateApiApiDecrypt(ciphertextWithNonce: ciphertextWithNonce, key: key);

/// Derive a 32-byte vault encryption key from `password` and `salt`.
///
/// Parameters: t=3, m=64 MiB, p=4 (OWASP MASVS L2).
/// The `salt` must be at least 16 bytes; store it alongside the vault.
/// Async — runs on Rust worker thread to avoid blocking Flutter UI.
Future<Uint8List> apiDeriveKey(
        {required List<int> password, required List<int> salt}) =>
    RustLib.instance.api.crateApiApiDeriveKey(password: password, salt: salt);

/// Hash `password` using Argon2id with a random salt.
/// Returns a PHC-format string suitable for server-side auth.
/// Async — runs on Rust worker thread to avoid blocking Flutter UI.
Future<String> apiHashPassword({required String password}) =>
    RustLib.instance.api.crateApiApiHashPassword(password: password);

/// Verify `password` against a PHC hash string.
/// Returns `true` on match, `false` on mismatch.
/// Async — runs on Rust worker thread to avoid blocking Flutter UI.
Future<bool> apiVerifyPassword(
        {required String password, required String hash}) =>
    RustLib.instance.api
        .crateApiApiVerifyPassword(password: password, hash: hash);

/// Generate a cryptographically random password.
String apiGeneratePassword({required ApiGeneratorConfig config}) =>
    RustLib.instance.api.crateApiApiGeneratePassword(config: config);

/// Config for `api_generate_password`.
class ApiGeneratorConfig {
  final BigInt length;
  final bool useLowercase;
  final bool useUppercase;
  final bool useDigits;
  final bool useSymbols;

  const ApiGeneratorConfig({
    required this.length,
    required this.useLowercase,
    required this.useUppercase,
    required this.useDigits,
    required this.useSymbols,
  });

  @override
  int get hashCode =>
      length.hashCode ^
      useLowercase.hashCode ^
      useUppercase.hashCode ^
      useDigits.hashCode ^
      useSymbols.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiGeneratorConfig &&
          runtimeType == other.runtimeType &&
          length == other.length &&
          useLowercase == other.useLowercase &&
          useUppercase == other.useUppercase &&
          useDigits == other.useDigits &&
          useSymbols == other.useSymbols;
}
