import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

import 'firebase_options.dart';

/// Initialises Firebase once at app startup.
///
/// Call [FirebaseService.init] inside main() before [runApp].
/// Uses [DefaultFirebaseOptions] generated by `flutterfire configure`
/// or defined manually in firebase_options.dart.
class FirebaseService {
  FirebaseService._();

  static bool _initialized = false;

  static Future<void> init() async {
    if (_initialized) return;
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      _initialized = true;
    } catch (e) {
      // Firebase is optional — app continues without it.
      debugPrint('[FirebaseService] Init skipped: $e');
    }
  }
}
